title: Isaac Sheldrake,  Wildlife Blogger

#########################
# footer details

email: isaac@wild-me.co.uk
twitter-handle: wildmeUK
description: <strong>I am Isaac Sheldrake</strong> This is my blog. I love to investigate nature and would like to share with you what I have found. This blog will grow and change as I discover new things. I hope you enjoy it!

#########################
# Header details and images
header-title: Wild-me.co.uk
index-page-img: isaac-meg.jpg
about-page-img: isaac-beach.jpg